#pragma config(Sensor, dgtl4,  startButton,    sensorTouch)
#pragma config(Sensor, dgtl5,  HIT,            sensorTouch)
#pragma config(Motor,  port8,           motor2,        tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           motor1,        tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

bool onSwitch = false;
bool turn1Switch = false;
bool turn2Switch = false;

task main()
{
  while(1==1)
  {
	 if (SensorValue(startButton) == 1 && onSwitch == false)
	 {
	   onSwitch = true;
		 startMotor(motor1, 80);
		 startMotor(motor2, 80);
	 }
   if (SensorValue(HIT)== 1 && turn1Switch == false)
	  //initiate turn 1
	 {
	   turn1Switch = true;
	   stopMotor(motor1);
	   stopMotor(motor2);
	   wait(0.5);
	   //reverse
	   startMotor(motor1, -100);
		 startMotor(motor2, -100);
		 wait(0.5);
		 //turn
	   startMotor(motor1, 127);
		 startMotor(motor2, -127);
		 wait(0.3);
		 //go forward
		 startMotor(motor1, 80);
		 startMotor(motor2, 80);
	}
	if (SensorValue(HIT)== 1 && turn1Switch == false)
	  //initiate turn 1
	 {
	   turn1Switch = true;
	   stopMotor(motor1);
	   stopMotor(motor2);
	   wait(0.5);
	   //reverse
	   startMotor(motor1, -100);
		 startMotor(motor2, -100);
		 wait(0.5);
		 //turn
	   startMotor(motor1, 127);
		 startMotor(motor2, -127);
		 wait(0.3);
		 //go forward
		 startMotor(motor1, 80);
		 startMotor(motor2, 80);
	}

	if (SensorValue(HIT)== 1 && turn2Switch == false)
	  //initiate turn 1
	 {
	   turn2Switch = true;
	   stopMotor(motor1);
	   stopMotor(motor2);
	   wait(0.5);
	   //reverse
	   startMotor(motor1, -100);
		 startMotor(motor2, -100);
		 wait(0.5);
		 //turn
	   startMotor(motor1, -127);
		 startMotor(motor2, 127);
		 wait(0.3);
		 //go forward
		 startMotor(motor1, 80);
		 startMotor(motor2, 80);
	}


  }

}
